const SURL='https://ufcycbsrpnfrjeculmtd.supabase.co';
const SKEY='sb_publishable_EGDpH9JqVOFRgpM_p3UnLA_MT8TfhoX';
const EDGE_UPLOAD=SURL+'/functions/v1/drime-upload';
const db=window.supabase.createClient(SURL,SKEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let me=null, myProfile=null, brotherProfile=null, items=[], stateMap=new Map(), selectedFiles=[], presenceChannel=null, previewUrls=[], storageAvailableBytes=20*1024**3;

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtBytes=n=>{n=Number(n||0);if(n<1024)return n+' B';const u=['KB','MB','GB','TB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return n.toFixed(n<10?1:0)+' '+u[i]};
const fmtDate=s=>new Date(s).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'});
const ext=n=>{const p=n.lastIndexOf('.');return p>0?n.slice(p+1).toLowerCase():''};
function errorText(value,fallback='No se pudo completar la operación.'){
  if(typeof value==='string'&&value.trim())return value;
  if(value instanceof Error&&value.message)return value.message;
  if(value&&typeof value==='object'){
    for(const key of ['message','error','details','hint','code']){
      if(value[key]!==undefined&&value[key]!==value){const text=errorText(value[key],'');if(text)return text}
    }
    try{const text=JSON.stringify(value);if(text&&text!=='{}')return text}catch{}
  }
  return fallback;
}

async function api(path,opt={}){const {data}=await db.auth.getSession();const token=data.session?.access_token;if(!token)throw Error('Sesión caducada');const h=new Headers(opt.headers||{});h.set('Authorization','Bearer '+token);if(opt.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await fetch(path,{...opt,headers:h});const ct=r.headers.get('content-type')||'';const v=ct.includes('json')?await r.json():await r.text();if(!r.ok)throw Error(errorText(v?.error??v?.message??v,'Error '+r.status));return v}
async function edgeUpload(action,body,headers={}){const {data}=await db.auth.getSession();const token=data.session?.access_token;if(!token)throw Error('Sesión caducada');const r=await fetch(EDGE_UPLOAD+'?action='+encodeURIComponent(action),{method:'POST',headers:{Authorization:'Bearer '+token,...headers},body});if(!r.ok){let detail='Error de subida '+r.status;try{const j=await r.json();detail=errorText(j?.error??j?.message??j,detail)}catch{}throw Error(detail)}return r}

function showAuthError(m=''){$('#authError').textContent=m}
const GOOGLE_REDIRECT='https://brolink.vercel.app';
$('#googleBtn').onclick=async()=>{showAuthError('Abriendo Google…');const {data,error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:GOOGLE_REDIRECT,skipBrowserRedirect:true}});if(error){showAuthError(error.message);return}if(data?.url){window.location.assign(data.url);return}showAuthError('No se pudo abrir Google. Recarga la página y prueba de nuevo.');};
$('#loginBtn').onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$('#authEmail').value.trim(),password:$('#authPassword').value});showAuthError(error?.message||'')};
$('#signupBtn').onclick=async()=>{const {error}=await db.auth.signUp({email:$('#authEmail').value.trim(),password:$('#authPassword').value});showAuthError(error?.message||'Cuenta creada. Revisa tu correo si se solicita confirmación.')};
$('#resetBtn').onclick=async()=>{const e=$('#authEmail').value.trim();if(!e)return showAuthError('Escribe primero tu correo.');const {error}=await db.auth.resetPasswordForEmail(e,{redirectTo:GOOGLE_REDIRECT});showAuthError(error?.message||'Te hemos enviado el enlace de recuperación.')};

async function avatarUrl(path){if(!path)return'';if(/^https?:\/\//i.test(path))return path;const {data,error}=await db.storage.from('avatars').createSignedUrl(path,3600);return error?'':data?.signedUrl||''}
async function paintAvatar(el,path,initial='U'){if(!el)return;const u=await avatarUrl(path);el.style.backgroundImage=u?'url("'+u.replace(/"/g,'%22')+'")':'';el.style.backgroundSize='cover';el.style.backgroundPosition='center';el.textContent=u?'':initial}
async function uploadAvatar(file){if(!file)return myProfile?.avatar_url||null;if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('La foto debe ser PNG, JPG o WebP.');if(file.size>2*1024*1024)throw Error('La foto no puede superar 2 MB.');const path=me.id+'/avatar';const {error}=await db.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(error)throw error;return path}

async function loadProfiles(){const {data,error}=await db.from('profiles').select('id,display_name,avatar_url,created_at').order('created_at',{ascending:true});if(error)throw error;myProfile=(data||[]).find(x=>x.id===me.id)||null;brotherProfile=(data||[]).find(x=>x.id!==me.id)||null;const name=myProfile?.display_name||me.user_metadata?.full_name||me.email?.split('@')[0]||'Usuario';$('#settingsName').textContent=name;$('#settingsEmail').textContent=me.email||'';$('#profileName').value=myProfile?.display_name||name;$('#newEmail').value=me.email||'';await paintAvatar($('#selfAvatar'),myProfile?.avatar_url||'',name[0]?.toUpperCase()||'T');await paintAvatar($('#settingsAvatar'),myProfile?.avatar_url||'',name[0]?.toUpperCase()||'U');if(brotherProfile){await paintAvatar($('#broAvatar'),brotherProfile.avatar_url||'',(brotherProfile.display_name||'H')[0].toUpperCase());$('#broStatus').textContent='Desconectado'}else{$('#broStatus').textContent='Sin cuenta todavía'} }

let syncRefreshTimer=null;
function scheduleRemoteRefresh(){clearTimeout(syncRefreshTimer);syncRefreshTimer=setTimeout(async()=>{if(!me)return;try{await loadProfiles();await refresh()}catch(e){console.warn('BroLink sync',e)}},180)}
async function syncOthers(reason='update'){try{if(presenceChannel)await presenceChannel.send({type:'broadcast',event:'data-changed',payload:{reason,user_id:me?.id||null,at:new Date().toISOString()}})}catch(e){console.warn('BroLink broadcast',e)}}
function startPresence(){if(presenceChannel)db.removeChannel(presenceChannel);presenceChannel=db.channel('brolink-presence',{config:{presence:{key:me.id}}});presenceChannel.on('presence',{event:'sync'},()=>{const state=presenceChannel.presenceState();const online=new Set();Object.values(state).flat().forEach(p=>p.user_id&&online.add(p.user_id));if(brotherProfile&&online.has(brotherProfile.id)){$('#broStatus').textContent='Conectado';$('#broDot').classList.remove('off')}else{$('#broStatus').textContent=brotherProfile?'Desconectado':'Sin cuenta todavía';$('#broDot').classList.add('off')}}).on('broadcast',{event:'data-changed'},()=>scheduleRemoteRefresh()).subscribe(async s=>{if(s==='SUBSCRIBED')await presenceChannel.track({user_id:me.id,at:new Date().toISOString()})})}

async function loadStates(){const {data,error}=await db.from('item_user_state').select('*').eq('user_id',me.id);if(error)throw error;stateMap=new Map((data||[]).map(s=>[s.item_id,s]))}
function stateFor(id){return stateMap.get(id)||{user_id:me.id,item_id:id,is_favorite:false,trashed_at:null}}
async function patchState(itemId,patch){const s=stateFor(itemId);const row={user_id:me.id,item_id:itemId,is_favorite:s.is_favorite||false,trashed_at:s.trashed_at||null,...patch,updated_at:new Date().toISOString()};const {error}=await db.from('item_user_state').upsert(row,{onConflict:'user_id,item_id'});if(error)throw error;await refresh()}

function typeClass(i){const e=ext(i.title||'');if(e==='pdf')return'pdf';if(['zip','rar','7z'].includes(e))return'zip';if(i.kind==='link')return'link';if(i.kind==='note')return'note';return''}
function typeIcon(i){const e=ext(i.title||'');if(e==='pdf')return'<svg class="icon"><path d="M7 3h7l4 4v14H7zM14 3v5h5M10 14h4M10 17h4"/></svg>';if(['zip','rar','7z'].includes(e))return'<svg class="icon"><path d="M8 3h8v18H8zM11 3v3M11 8v2M11 12v2M11 16v2"/></svg>';if(i.kind==='link')return'<svg class="icon"><path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1M14 11a5 5 0 0 0-7.1-.1l-2 2A5 5 0 0 0 12 20l1.1-1.1"/></svg>';return'<svg class="icon"><path d="M7 3h7l4 4v14H7zM14 3v5h5"/></svg>'}
function statusText(i){return i.status==='downloaded'?'Descargado':i.status==='seen'?'Visto':'Nuevo'}
function itemHTML(i,trash=false){const s=stateFor(i.id),fav=!!s.is_favorite;const meta=i.kind==='file'?(fmtBytes(i.file_size)+' · '+fmtDate(i.created_at)):(i.url?'Enlace · ':'')+fmtDate(i.created_at);const action=i.kind==='file'&&i.drime_hash?`<button class="mini" title="Descargar" data-download="${i.id}"><svg class="icon sm"><path d="M12 3v12M8 11l4 4 4-4M5 20h14"/></svg></button>`:i.kind==='link'&&i.url?`<button class="mini" title="Abrir" data-open="${i.id}"><svg class="icon sm"><path d="M14 5h5v5M19 5l-8 8M18 13v6H5V6h6"/></svg></button>`:'';const favBtn=`<button class="mini ${fav?'on':''}" title="Favorito" data-fav="${i.id}"><svg class="icon sm"><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-2.9-5.6 2.9 1.1-6.2L3 9.6l6.2-.9z"/></svg></button>`;const trashBtn=trash?`<button class="mini" title="Restaurar" data-restore="${i.id}"><svg class="icon sm"><path d="M4 8v5h5M5 12a7 7 0 1 0 2-5"/></svg></button>${i.sender_id===me.id?`<button class="mini danger" title="Eliminar definitivamente" data-permanent="${i.id}"><svg class="icon sm"><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14"/></svg></button>`:''}`:`<button class="mini danger" title="Papelera" data-trash="${i.id}"><svg class="icon sm"><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14"/></svg></button>`;return `<div class="item"><div class="item-type ${typeClass(i)}">${typeIcon(i)}</div><div class="item-title"><strong>${esc(i.title||'Sin título')}</strong><span>${esc(i.note||meta)}</span><div class="status ${i.status==='seen'?'seen':i.status==='downloaded'?'downloaded':''}">${statusText(i)}</div></div><div class="item-actions">${action}${favBtn}${trashBtn}</div></div>`}
function renderList(sel,list,trash=false){$(sel).innerHTML=list.length?list.map(i=>itemHTML(i,trash)).join(''):'<div class="empty">Todavía no hay elementos.</div>'}

async function refresh(){const {data,error}=await db.from('items').select('*').order('created_at',{ascending:false});if(error)throw error;items=data||[];await loadStates();const visible=items.filter(i=>!stateFor(i.id).trashed_at);const trash=items.filter(i=>!!stateFor(i.id).trashed_at);renderList('#mineList',visible.filter(i=>i.sender_id===me.id).slice(0,5));renderList('#otherList',visible.filter(i=>i.recipient_id===me.id).slice(0,5));renderList('#filesList',visible.filter(i=>i.kind==='file'));renderList('#historyList',visible);renderList('#favoritesList',visible.filter(i=>stateFor(i.id).is_favorite));renderList('#trashList',trash,true);bindItemActions();await storage()}

async function storage(){try{const h=await api('/api/drime/health'),used=+h.used||0,av=+h.available||0,total=Math.max(1,used+av),pct=Math.min(100,used/total*100);storageAvailableBytes=Math.max(0,av);$('#storageFill').style.width=pct+'%';$('#storagePct').textContent=pct.toFixed(1)+'%';$('#storageText').textContent=fmtBytes(used)+' de '+fmtBytes(total);if($('#uploadLimit'))$('#uploadLimit').textContent='Espacio disponible ahora: '+fmtBytes(storageAvailableBytes)+' ('+Math.floor(storageAvailableBytes/1024**2).toLocaleString('es-ES')+' MB) · archivos grandes se suben en bloques de 5 MB'}catch(e){const used=items.reduce((a,i)=>a+(i.file_size||0),0),total=20*1024**3,pct=Math.min(100,used/total*100);storageAvailableBytes=Math.max(0,total-used);$('#storageFill').style.width=pct+'%';$('#storagePct').textContent=pct.toFixed(1)+'%';$('#storageText').textContent=fmtBytes(used)+' de 20 GB';if($('#uploadLimit'))$('#uploadLimit').textContent='Espacio disponible estimado: '+fmtBytes(storageAvailableBytes)+' ('+Math.floor(storageAvailableBytes/1024**2).toLocaleString('es-ES')+' MB) · 20 GB totales'}}

async function uploadToDrime(file,onProgress){const meta={filename:file.name,mime:file.type||'application/octet-stream',size:file.size,extension:ext(file.name)};let entry;if(file.size<5*1024*1024){const r=await edgeUpload('small',file,{'Content-Type':meta.mime,'x-file-name':encodeURIComponent(file.name),'x-file-mime':meta.mime,'x-file-size':String(file.size),'x-file-extension':meta.extension});const z=await r.json();entry=z.fileEntry||z}else{const size=5*1024*1024,c=await api('/api/drime/multipart/create',{method:'POST',body:JSON.stringify(meta)}),n=Math.ceil(file.size/size),parts=[];for(let p=1;p<=n;p++){onProgress?.(p,n);const chunk=file.slice((p-1)*size,Math.min(p*size,file.size)),r=await edgeUpload('part',chunk,{'Content-Type':'application/octet-stream','x-upload-key':encodeURIComponent(c.key),'x-upload-id':c.uploadId,'x-part-number':String(p)}),etag=r.headers.get('etag');if(!etag)throw Error('Drime no confirmó una de las partes del archivo.');parts.push({PartNumber:p,ETag:etag})}await api('/api/drime/multipart/complete',{method:'POST',body:JSON.stringify({key:c.key,uploadId:c.uploadId,parts})});const z=await api('/api/drime/register',{method:'POST',body:JSON.stringify({key:c.key,size:file.size,clientName:file.name,clientMime:meta.mime,clientExtension:meta.extension})});entry=z.fileEntry||z}if(!entry?.id||!entry?.hash)throw Error('Drime no confirmó correctamente el archivo. Inténtalo de nuevo.');return entry}
function clearFilePreviews(){previewUrls.forEach(u=>URL.revokeObjectURL(u));previewUrls=[];const box=$('#filePreview');if(box){box.innerHTML='';box.classList.add('hidden')}}function stageFiles(files){clearFilePreviews();selectedFiles=[...files];const total=selectedFiles.reduce((a,f)=>a+f.size,0);$('#fileSelected').textContent=selectedFiles.length?(selectedFiles.length+' archivo'+(selectedFiles.length===1?'':'s')+' · '+fmtBytes(total)):'';const box=$('#filePreview');if(!box||!selectedFiles.length)return;box.classList.remove('hidden');selectedFiles.forEach(f=>{const card=document.createElement('div');card.className='preview-card';if(f.type&&f.type.startsWith('image/')){const u=URL.createObjectURL(f);previewUrls.push(u);const img=document.createElement('img');img.className='preview-thumb';img.src=u;img.alt='Previsualización de '+f.name;card.appendChild(img)}else{const ico=document.createElement('div');ico.className='preview-file';ico.textContent='📄';card.appendChild(ico)}const meta=document.createElement('div');meta.className='preview-meta';const strong=document.createElement('strong');strong.textContent=f.name;const span=document.createElement('span');span.textContent=fmtBytes(f.size);meta.append(strong,span);card.appendChild(meta);box.appendChild(card)});if(total>storageAvailableBytes){const n=$('#uploadNotice');n.classList.remove('hidden');n.textContent='Has seleccionado '+fmtBytes(total)+', pero solo quedan '+fmtBytes(storageAvailableBytes)+' disponibles.'}}
$('#fileInput').onchange=e=>stageFiles(e.target.files);['dragenter','dragover'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').style.borderColor='#7ac8ff'}));['dragleave','drop'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').style.borderColor=''}));$('#dropzone').addEventListener('drop',e=>stageFiles(e.dataTransfer.files));
$('#sendFiles').onclick=async()=>{const note=$('#fileMessage').value.trim(),n=$('#uploadNotice');n.classList.remove('hidden');if(!brotherProfile){n.textContent='Tu hermano todavía no ha creado su cuenta.';return}if(!selectedFiles.length){n.textContent='Selecciona al menos un archivo.';return}const totalBytes=selectedFiles.reduce((a,f)=>a+f.size,0);if(totalBytes>storageAvailableBytes){n.textContent='No hay espacio suficiente: seleccionaste '+fmtBytes(totalBytes)+' y quedan '+fmtBytes(storageAvailableBytes)+'.';return}try{for(const f of selectedFiles){n.textContent='Subiendo '+f.name+'…';const entry=await uploadToDrime(f,(p,t)=>n.textContent=f.name+': parte '+p+' de '+t+'…');const {error}=await db.from('items').insert({sender_id:me.id,recipient_id:brotherProfile.id,kind:'file',title:f.name,note:note||null,file_size:f.size,mime_type:f.type||'application/octet-stream',drime_file_id:String(entry.id),drime_hash:entry.hash,status:'new'});if(error)throw error}n.textContent='Envío completado.';selectedFiles=[];clearFilePreviews();$('#fileInput').value='';$('#fileSelected').textContent='';$('#fileMessage').value='';await refresh();await syncOthers('file-sent')}catch(e){console.error('BroLink envío',e);n.textContent=errorText(e,'No se pudo enviar el archivo. Inténtalo de nuevo.')}}
$('#sendLink').onclick=async()=>{if(!brotherProfile)return alert('Tu hermano todavía no ha creado su cuenta.');const url=$('#linkUrl').value.trim(),note=$('#linkNote').value.trim();if(!url&&!note)return alert('Escribe un enlace o un mensaje.');const {error}=await db.from('items').insert({sender_id:me.id,recipient_id:brotherProfile.id,kind:url?'link':'note',title:url||'Nota',url:url||null,note:note||null,status:'new'});if(error)return alert(error.message);$('#linkUrl').value='';$('#linkNote').value='';await refresh();await syncOthers('link-sent')}

async function downloadItem(i){try{const {data}=await db.auth.getSession(),r=await fetch('/api/drime/download/'+encodeURIComponent(i.drime_hash),{headers:{Authorization:'Bearer '+data.session.access_token}});if(!r.ok)throw Error('No se pudo descargar');const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=i.title||'archivo';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);if(i.recipient_id===me.id){await db.from('items').update({status:'downloaded',seen_at:i.seen_at||new Date().toISOString(),downloaded_at:new Date().toISOString()}).eq('id',i.id).eq('recipient_id',me.id);await refresh();await syncOthers('downloaded')}}catch(e){alert(errorText(e,'No se pudo descargar el archivo.'))}}
async function permanentDelete(i){if(i.sender_id!==me.id)return;if(!confirm('Esto borrará el elemento para los dos. ¿Continuar?'))return;try{if(i.kind==='file'&&i.drime_file_id)await api('/api/drime/delete',{method:'POST',body:JSON.stringify({entryIds:[Number(i.drime_file_id)]})});const {error}=await db.from('items').delete().eq('id',i.id).eq('sender_id',me.id);if(error)throw error;await refresh();await syncOthers('deleted')}catch(e){alert(errorText(e,'No se pudo eliminar el elemento.'))}}
function bindItemActions(){$$('[data-download]').forEach(b=>b.onclick=()=>{const i=items.find(x=>x.id===b.dataset.download);if(i)downloadItem(i)});$$('[data-open]').forEach(b=>b.onclick=async()=>{const i=items.find(x=>x.id===b.dataset.open);if(!i)return;if(i.recipient_id===me.id&&i.status==='new')await db.from('items').update({status:'seen',seen_at:new Date().toISOString()}).eq('id',i.id).eq('recipient_id',me.id);window.open(i.url,'_blank','noopener');await refresh();await syncOthers('seen')});$$('[data-fav]').forEach(b=>b.onclick=()=>{const s=stateFor(b.dataset.fav);patchState(b.dataset.fav,{is_favorite:!s.is_favorite})});$$('[data-trash]').forEach(b=>b.onclick=()=>patchState(b.dataset.trash,{trashed_at:new Date().toISOString()}));$$('[data-restore]').forEach(b=>b.onclick=()=>patchState(b.dataset.restore,{trashed_at:null}));$$('[data-permanent]').forEach(b=>b.onclick=()=>{const i=items.find(x=>x.id===b.dataset.permanent);if(i)permanentDelete(i)})}

function showView(id,focus){$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+id).classList.remove('hidden');$$('.nav button').forEach(b=>b.classList.remove('active'));const btn=$$('.nav button').find(b=>b.dataset.view===id&&(!focus||b.dataset.focus===focus))||$$('.nav button').find(b=>b.dataset.view===id&&!b.dataset.focus);if(btn)btn.classList.add('active');if(focus==='file')setTimeout(()=>$('#filePanel').scrollIntoView({behavior:'smooth',block:'center'}),50);if(focus==='link')setTimeout(()=>$('#linkPanel').scrollIntoView({behavior:'smooth',block:'center'}),50)}
$$('.nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view,b.dataset.focus));$$('[data-view-jump]').forEach(b=>b.onclick=()=>showView(b.dataset.viewJump));

$('#saveProfile').onclick=async()=>{const box=$('#profileNotice');box.classList.remove('hidden');try{const name=$('#profileName').value.trim(),file=$('#profileAvatarFile').files?.[0],avatar=await uploadAvatar(file);const {error}=await db.from('profiles').update({display_name:name,avatar_url:avatar,updated_at:new Date().toISOString()}).eq('id',me.id);if(error)throw error;box.textContent='Perfil guardado.';$('#profileAvatarFile').value='';await loadProfiles();await syncOthers('profile')}catch(e){box.textContent=errorText(e,'No se pudo guardar el perfil.')}}
$('#saveAccount').onclick=async()=>{const o={};if($('#newEmail').value&&$('#newEmail').value!==me.email)o.email=$('#newEmail').value;if($('#newPassword').value)o.password=$('#newPassword').value;if(!Object.keys(o).length)return alert('No hay cambios.');const {error}=await db.auth.updateUser(o);alert(error?error.message:'Cuenta actualizada.');$('#newPassword').value=''};
async function logout(){if(presenceChannel)await presenceChannel.untrack().catch(()=>{});await db.auth.signOut()}$('#logoutTop').onclick=logout;$('#logoutSettings').onclick=logout;

async function enter(session){me=session.user;$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');await loadProfiles();startPresence();await refresh();showView('inicio')}
function leave(){$('#app').classList.add('hidden');$('#authScreen').classList.remove('hidden');me=myProfile=brotherProfile=null;items=[];stateMap=new Map();selectedFiles=[]}
db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>s?enter(s):leave(),0));(async()=>{const {data}=await db.auth.getSession();data.session?enter(data.session):leave()})();
